# Generated by Django 3.2.14 on 2022-07-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='published_date',
            new_name='Finished_date',
        ),
        migrations.AddField(
            model_name='task',
            name='Status',
            field=models.BooleanField(default=False),
        ),
    ]
