# Generated by Django 3.2.14 on 2022-07-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20220719_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Finished_date',
            new_name='finished_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
